/* Generated by tools/generate-protocol-vectors.py; do not hand-edit.
 * ESP32SPI source SHA256: e282db39a2f52e6fb42b54f4e649d0ba772e60fbd275a67effb6db27f303646e
 * Reference: nina-fw 3.3.0, 586ef2a, main/CommandHandler.cpp. */
static const struct { const char *name, *request, *response; } golden[] = {
    {"version", "e03700ee", "e0b70110332e332e302b72746c383732302e3100ee000000"},
    {"status", "e02000ee", "e0a0010103ee0000"},
    {"open", "e010010474657374ee000000", "e090010101ee0000"},
    {"wpa2", "e0110204746573740870617373776f7264ee0000", "e091010101ee0000"},
    {"static_ip", "e01404010004c000020a04c000020104ffffff00ee000000", "e094010101ee0000"},
    {"dns_config", "e01503010004c00002010401010101ee", "e095010101ee0000"},
    {"hostname", "e016010877696f2d74657374ee0101ee", "e096010101ee0000"},
    {"address", "e0210101ffee6f2d", "e0a10304c000020a04ffffff0004c0000201ee00"},
    {"mac", "e0220101ffee6f2d", "e0a20106050403020100ee00"},
    {"ssid", "e0230101ffee6f2d", "e0a3010474657374ee000000"},
    {"bssid", "e0240101ffee6f2d", "e0a40106000102030405ee00"},
    {"rssi", "e0250101ffee6f2d", "e0a50104d6ffffffee000000"},
    {"encryption", "e0260101ffee6f2d", "e0a6010104ee0000"},
    {"scan_start", "e03600ee", "e0b6010101ee0000"},
    {"scan_results", "e02700ee", "e0a702047465737400ee0000"},
    {"indexed_rssi", "e032010100ee6f2d", "e0b20104d6ffffffee000000"},
    {"indexed_encryption", "e033010100ee6f2d", "e0b3010104ee0000"},
    {"indexed_bssid", "e03c010100ee6f2d", "e0bc0106000102030405ee00"},
    {"indexed_channel", "e03d010100ee6f2d", "e0bd010106ee0000"},
    {"dns_request", "e034010b6578616d706c652e636f6dee", "e0b4010101ee0000"},
    {"dns_result", "e03500ee", "e0b50104c0000250ee000000"},
    {"ping", "e03e0204c000020101faee2e", "e0be01023412ee00"},
    {"disconnect", "e03000ee", "e0b0010101ee0000"},
};
