"""Print a C fixture header using ESP32SPI 11.1.4's actual _send_command.

Usage: python3 tools/generate-protocol-vectors.py /path/to/adafruit_esp32spi.py
The adjacent driver/reference are development oracles, never build inputs.
Only the parsed command method executes; no hardware imports are required.
Expected response shapes were cross-checked with nina-fw 3.3.0 (586ef2a),
main/CommandHandler.cpp. Backend values below are deterministic mock values.
"""
import ast
import hashlib
from pathlib import Path
import sys
import time
from types import SimpleNamespace

source = Path(sys.argv[1]).read_text()
if '__version__ = "11.1.4"' not in source:
    raise SystemExit('Expected the released ESP32SPI 11.1.4 source')
tree = ast.parse(source)
cls = next(n for n in tree.body if isinstance(n, ast.ClassDef) and n.name == 'ESP_SPIcontrol')
method = next(n for n in cls.body if isinstance(n, ast.FunctionDef) and n.name == '_send_command')
namespace = dict(time=time, _START_CMD=0xe0, _END_CMD=0xee, _REPLY_FLAG=0x80)
exec(compile(ast.Module(body=[method], type_ignores=[]), '<ESP32SPI 11.1.4 _send_command>', 'exec'), namespace)


class Capture:
    def __enter__(self):
        return self

    def __exit__(self, *_):
        pass

    def write(self, buffer, *, start, end):
        self.packet = bytes(buffer[start:end])


capture = Capture()
harness = SimpleNamespace(_sendbuf=bytearray(256), _debug=0,
                          _wait_for_ready=lambda: None, _spi_device=capture,
                          _ready=SimpleNamespace(value=True))
ip, gateway, mask = bytes([192, 0, 2, 10]), bytes([192, 0, 2, 1]), bytes([255, 255, 255, 0])
yes, dummy, index = b'\1', b'\xff', b'\0'
cases = [
    ('version', 0x37, [], [b'3.3.0+rtl8720.1\0']),
    ('status', 0x20, [], [b'\3']),
    ('open', 0x10, [b'test'], [yes]),
    ('wpa2', 0x11, [b'test', b'password'], [yes]),
    ('static_ip', 0x14, [index, ip, gateway, mask], [yes]),
    ('dns_config', 0x15, [index, gateway, bytes([1, 1, 1, 1])], [yes]),
    ('hostname', 0x16, [b'wio-test'], [yes]),
    ('address', 0x21, [dummy], [ip, mask, gateway]),
    ('mac', 0x22, [dummy], [bytes([5, 4, 3, 2, 1, 0])]),
    ('ssid', 0x23, [dummy], [b'test']),
    ('bssid', 0x24, [dummy], [bytes([0, 1, 2, 3, 4, 5])]),
    ('rssi', 0x25, [dummy], [bytes.fromhex('d6ffffff')]),
    ('encryption', 0x26, [dummy], [b'\4']),
    ('scan_start', 0x36, [], [yes]),
    ('scan_results', 0x27, [], [b'test', b'']),
    ('indexed_rssi', 0x32, [index], [bytes.fromhex('d6ffffff')]),
    ('indexed_encryption', 0x33, [index], [b'\4']),
    ('indexed_bssid', 0x3c, [index], [bytes([0, 1, 2, 3, 4, 5])]),
    ('indexed_channel', 0x3d, [index], [b'\6']),
    ('dns_request', 0x34, [b'example.com'], [yes]),
    ('dns_result', 0x35, [], [bytes([192, 0, 2, 80])]),
    ('ping', 0x3e, [gateway, b'\xfa'], [b'\x34\x12']),
    ('disconnect', 0x30, [], [yes]),
]
print('/* Generated by tools/generate-protocol-vectors.py; do not hand-edit.')
print(' * ESP32SPI source SHA256:', hashlib.sha256(source.encode()).hexdigest())
print(' * Reference: nina-fw 3.3.0, 586ef2a, main/CommandHandler.cpp. */')
print('static const struct { const char *name, *request, *response; } golden[] = {')
for name, command, params, expected in cases:
    namespace['_send_command'](harness, command, params)
    response = bytes([0xe0, command | 0x80, len(expected)])
    for param in expected:
        response += bytes([len(param)]) + param
    response += b'\xee'
    response += bytes(-len(response) % 4)
    print(f'    {{"{name}", "{capture.packet.hex()}", "{response.hex()}"}},')
print('};')
