#!/usr/bin/env python3
"""Explicit, offline selection from curl's Mozilla server-auth PEM export."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
NAMES = ('ISRG Root X1', 'DigiCert Global Root G2', 'GlobalSign Root CA - R3', 'Amazon Root CA 1')

def generate(data):
    text = data.decode('utf-8')
    certs = []
    for name in NAMES:
        match = re.search(r'^' + re.escape(name) + r'\n=+\n(-----BEGIN CERTIFICATE-----\n.*?-----END CERTIFICATE-----\n)', text, re.M | re.S)
        if not match:
            raise ValueError('Missing root: ' + name)
        certs.append(match.group(1))
    return ''.join(certs).encode('ascii')

def header(pem):
    return ('/* Generated by tools/update-certificates.py; do not edit. */\n'
            'static const unsigned char nina_roots_pem[] =\n' +
            ''.join(json.dumps(line + '\n') + '\n' for line in pem.decode().splitlines()) + ';\n')

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input', type=Path)
    parser.add_argument('--source-url', required=True)
    parser.add_argument('--source-date', required=True)
    parser.add_argument('--sha256', required=True)
    args = parser.parse_args()
    data = args.input.read_bytes()
    if hashlib.sha256(data).hexdigest() != args.sha256:
        raise SystemExit('Input SHA-256 mismatch')
    pem = generate(data)
    folder = ROOT / 'certificates'
    folder.mkdir(exist_ok=True)
    (folder / 'roots.pem').write_bytes(pem)
    (ROOT / 'src/nina/nina_roots.h').write_text(header(pem))
    metadata = dict(mozilla_source='https://hg.mozilla.org/projects/nss/file/tip/lib/ckfw/builtins/certdata.txt',
        source_url=args.source_url, source_date=args.source_date, input_sha256=args.sha256,
        roots=list(NAMES), pem_sha256=hashlib.sha256(pem).hexdigest(),
        generation_command=f'python3 tools/update-certificates.py INPUT.pem --source-url {args.source_url} --source-date {args.source_date} --sha256 {args.sha256}')
    (folder / 'metadata.json').write_text(json.dumps(metadata, indent=2) + '\n')

if __name__ == '__main__':
    main()
